openapi: 3.0.2
info:
  version: 1.0.0
  title: Common Geo-Registry REST API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  x-logo:
    url: '../docs/cgr_logo.png'
  description: >
    TODO: this************
externalDocs:
  description: Learn more about the Common Geo-Registry Specification.
  url: 'https://github.com/terraframe/common-geo-registry-specification'
tags:
  - name: GeoObject
    description: Operations to interact with GeoObjects in the CGR.
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  '/geoobject/get-all':
    $ref: 'paths/geoobject@get-all.yaml'
  '/geoobjecttype/get-all':
    $ref: 'paths/geoobjecttype@get-all.yaml'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []  # <-- use the same name here
